/*
 * Rest API to create/fetch accounts in Finkit system
 * A simple API to learn how to write OpenAPI Specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AccountDetails;
import io.swagger.client.model.Accounts;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Creates an account
     *
     * Adds a new account to the Finkit system.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountTest() throws ApiException {
        AccountDetails accountDetails = null;
        // api.createAccount(accountDetails);

        // TODO: test validations
    }
    
    /**
     * Account details delete
     *
     * Deletes the account details for the given accountNumber
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleetAccountTest() throws ApiException {
        Integer accountNumber = null;
        // api.deleetAccount(accountNumber);

        // TODO: test validations
    }
    
    /**
     * Gets the account details for the given account number
     *
     * Returns teh account details for the given account number
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountDetailsTest() throws ApiException {
        Integer accountNumber = null;
        // AccountDetails response = api.getAccountDetails(accountNumber);

        // TODO: test validations
    }
    
    /**
     * Gets account details
     *
     * Returns a list containing all account details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllAccountsTest() throws ApiException {
        // Accounts response = api.getAllAccounts();

        // TODO: test validations
    }
    
    /**
     * Account details update
     *
     * Updates the account details for the given accountNumber
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateAccountDetailsTest() throws ApiException {
        Integer accountNumber = null;
        // api.updateAccountDetails(accountNumber);

        // TODO: test validations
    }
    
}
